version: '3'
services:
  # Database and services containers
  db:
    #image: postgres:9.6.3
    image: mdillon/postgis
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 64m

  redis:
    image: redis:3.2.9-32bit
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 32m
        reservations:
          memory: 32m

  # Application containers
#  resque:
#    extends:
#      file: docker-services.yml
#      service: rails
#    command: sh -c 'QUEUES=live,fetch bundle exec rake resque:workers COUNT=3'
#    links:
#      - db
#      - redis
#    restart: always
#    logging:
#      driver: "json-file"
#      options:
#        max-size: 100k
##
#  cron:
#    extends:
#      file: docker-services.yml
#      service: rails
#    command: bundle exec rake resque:scheduler
#    links:
#      - redis
#    mem_limit: 128m

#  messaging:
#    build: ./compose/ruby/
#    volumes:
#      - .:/usr/src/app/
#    env_file: ./compose/.env
#    expose:
#      - "3000"
#    environment:
#      RACK_ENV: "development"
#      RAILS_ENV: "development"
#      PORT: "3000"
#      TERM_CHILD: "1"
#      RESQUE_TERM_TIMEOUT: "7"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: 100k
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
#    ports:
#      - "3001:3000"
#    links:
#      - db
#      - redis
#      - mailcatcher
#    deploy:
#      resources:
#        limits:
#          memory: 128m
#        reservations:
#          memory: 16m

  web:
    build: .
    volumes:
      - .:/usr/src/app/
    env_file: .env
    expose:
      - "3000"
    environment:
      RACK_ENV: "development"
      RAILS_ENV: "development"
      PORT: "3000"
      TERM_CHILD: "1"
      RESQUE_TERM_TIMEOUT: "7"
    logging:
      driver: "json-file"
      options:
        max-size: 100k
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3001:3000"
    links:
      - db
      - redis
      - mailcatcher
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 16m

  # Mocks containers
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 16m
